default: &default
  adapter: postgresql
  encoding: unicode
  username: cookterest
  password: cookpass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cockterest
test:
  <<: *default
  database: cockterest_test

production:
  <<: *default
  database: cockterest_production
